[option]
indent = 2

[rules]
# Design Intent
blocking_assignment_in_always_ff = true
blocking_assignment_in_always_latch = true
non_blocking_assignment_in_always_comb = true
case_default = true
enum_with_type = true
function_with_automatic = true
keyword_forbidden_priority = true
keyword_forbidden_unique = true
keyword_forbidden_unique0 = true
level_sensitive_always = true # Redundant with keyword_forbidden_always.
operator_case_equality = true
action_block_with_side_effect = true
default_nettype_none = true
function_same_as_system_function = true
keyword_forbidden_always = true
keyword_forbidden_wire_reg = true
non_ansi_module = true
generate_case_with_label = true
generate_for_with_label = true
generate_if_with_label = true
localparam_type_twostate = true
parameter_type_twostate = true
localparam_explicit_type = true
parameter_explicit_type = true
parameter_default_value = true
parameter_in_generate = true
parameter_in_package = true
genvar_declaration_in_loop = true
genvar_declaration_out_loop = false
keyword_forbidden_generate = true
keyword_required_generate = false
explicit_case_default = true
# explicit_if_else = true
loop_statement_in_always_comb = true
loop_statement_in_always_ff = true
loop_statement_in_always_latch = true
# sequential_block_in_always_comb = true
# sequential_block_in_always_ff = true
# sequential_block_in_always_latch = true
multiline_for_begin = true
multiline_if_begin = true
# inout_with_tri = true
# input_with_var = true
# output_with_var = true
interface_port_with_modport = true

# Style
tab_character = true
style_indent = true
style_trailingwhitespace = true
style_operator_arithmetic = true
style_operator_boolean = true
style_operator_integer = true
style_operator_unary = true

# style_keyword_0or1space = true
# style_keyword_0space = true
# style_keyword_1or2space = true
# style_keyword_1space = true
style_keyword_construct = true
style_keyword_datatype = false # Overly restrictive.
style_keyword_end = true
style_keyword_maybelabel = true
style_keyword_new = true
style_keyword_newline = true
# style_commaleading = true
eventlist_or = true

# Mine
uppercamelcase_interface = true
uppercamelcase_module = true
uppercamelcase_package = true
